"""empty message

Revision ID: 138234550b37
Revises: 9ae11e8e099e
Create Date: 2017-08-01 14:53:36.719179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '138234550b37'
down_revision = '9ae11e8e099e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_breadlist_person_id', 'breadlist', type_='foreignkey')
    op.alter_column('breadlist', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key('fk_breadlist_person_id', 'breadlist', 'person',
                          ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_breadlist_person_id', 'breadlist', type_='foreignkey')
    op.alter_column('breadlist', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key('fk_breadlist_person_id', 'breadlist', 'person',
                          ['person_id'], ['id'])
    # ### end Alembic commands ###
