"""empty message

Revision ID: 9ae11e8e099e
Revises: 7a6ca54260de
Create Date: 2017-08-01 12:42:55.973627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ae11e8e099e'
down_revision = '7a6ca54260de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breadlist', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('person', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('person', sa.Column('token', sa.String(length=128), nullable=True))
    op.alter_column('person', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('person', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=191),
               nullable=False)
    op.alter_column('person', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=100),
               nullable=True)
    op.alter_column('person', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=191),
               nullable=True)
    op.alter_column('person', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('person', 'token')
    op.drop_column('person', 'is_admin')
    op.alter_column('breadlist', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
